restricted-commands:
  - rm
  - mkdir
  - cp
  - mv

flags:
  is-command-enabled: true
  is-diff-directory-enabled: false
  is-diff-files-enabled: false
  is-listing-enabled: false
  is-checksum-enabled: false
  is-processes-enabled: false
  is-ssh-list-enabled: false

sh-commands:
  commands:
    - java --version
    - python --version
    - rm text
  directories:
    - /script/directory1, /script/directory2
  files:
    - /script/file1, /script/file2
  checksums:
    - /script/file1, /script/file2
  processes:
    - test.jar
  listings:
    -/script/folder1
  ssh:
    -server@name
